### PR TITLE
Module to track who is the man (or woman) now, dog.

### PR DESCRIPTION
**Pull request by Deguerre**

### CODE REVIEW

**Comment by kkartaltepe** [comment]
I think you are swinging a database shaped hammer at a variable shaped nail. If there is only ever 1 man/woman dog at a time. Why not just use a simple variable to keep track (as your "hack" hints at)? Is persistence across restarts that important?

**Comment by kkartaltepe** [comment]
To fix up the dropping the entire database at once you can use something like
```
current = CurrentManOrWomanDog.get()
current.whoDog = newDog
. . .
```
that way you only update whatever the first row acquired from get is every time. It looks the the SQLObject site is down... So hopefully that comes back so the docs can be available again!

**Comment by Deguerre** [comment]
On 24/02/2015 2:14 pm, kkartaltepe wrote:
>
> I think you are swinging a database shaped hammer at a variable shaped 
> nail. If there is only ever 1 man/woman dog at a time. Why not just 
> use a simple variable to keep track (as your "hack" hints at)? Is 
> persistence across restarts that important?
>
Persistence was the reason I did it. I do not claim that this is a good
reason.

Andrew Bromage
(a.k.a Pseudonym73)

**Comment by Chronister** [comment]
Looks good, based on your demo in chat

**Pull request merged**
